### ISSUE TITLE
Add support for YouTube channel start pages

### ISSUE THREAD

**Issue by mimagind** [james-fray/YouTube-No-Buffer#1]
The extension currently prevents buffering of videos on standard youtube video pages (URL format https://www_youtube_com/watch?v=[video_id]).
It doesn't seem to support the same for videos embedded in channel start pages (URL format https://www_youtube_com/user/[channel_name]/featured/). Those still load and start playing automatically.

The issue seems to be in /src.safariextension/lib/firefox/firefox.js at line 174.
if (!url.contains('youtube.com/watch?v=')) {
        return;
}

**Comment by james-fray** [comment]
Use the WebExtension version instead;
https://addons.mozilla.org/en-US/firefox/addon/youtube-no-buffer-autoplay/?src=search

Make sure to disable the SDK version first.
