### ISSUE TITLE
Reloading the page is required to stop the video

### ISSUE THREAD

**Issue by ghost** [james-fray/YouTube-No-Buffer#2]
Videos autoplay when opened, and only reloading the page causes them to be stopped as intended.

Firefox 48.0
Ubuntu 16.04

**Comment by james-fray** [comment]
There is an issue with 48. Please wait for the new release
https://addons.mozilla.org/en-US/firefox/addon/youtube-no-buffer/versions/

**Comment by ghost** [comment]
This issue appears to be resolved in 0.1.5.
