### ISSUE TITLE
Conflict with other extension

### ISSUE THREAD

**Issue by tberghuis** [james-fray/YouTube-No-Buffer#5]
The fix you did 3 days ago worked, then stopped working yesterday. Upgraded to the latest fix this morning but it's not working.

**Comment by tberghuis** [comment]
I got it to work again. Issue was caused by a conflict with another extension "Your quality for youtube" https://chrome.google.com/webstore/detail/your-quality-for-youtube/nfcilgimggemnogfigihdkmapdhhlbph?utm_source=chrome-app-launcher-info-dialog

**Comment by tberghuis** [comment]
Reopening because it would be nice to be able to use both extensions at the same time.

**Comment by james-fray** [comment]
I have a YouTube HD extension which is kind of similar; https://add0n.com/youtube-tools.html
 
> it would be nice to be able to use both extensions at the same time.

Most likely the other add-on also has a listener for quality changes and hence it is not possible to have both listeners (YouTube only accepts one)

**Comment by tberghuis** [comment]
Works great, thanks for your work. How you managed to figure out how youtubes javascript works is beyond me.
