### ISSUE TITLE
Bugged page loading/CPU usage on version 0.2.5

### ISSUE THREAD

**Issue by Remu-rin** [james-fray/YouTube-No-Buffer#6]
Problem url: https://www.youtube.com/yt/copyright/fair-use.html
Clean fresh profile: just never-ending high CPU usage, page doesn't finish loading (waited 10 min).
Customized profile with other extensions: high CPU usage, memory pull growth, then browser crashes completely.

Disabling extension fixes issue. Reproducible with and without e10s.

Both Firefox 55.0.3 (64-bit) and Nightly 57.0a1 (2017-09-03 build) (64-bit)
Windows 7

**Comment by james-fray** [comment]
This seems like an internal bug in WebEx. I've come up with a solution. Have you got into this problem in another page too?

**Comment by Remu-rin** [comment]
> Have you got into this problem in another page too?

Nope. Only that page and versions in another languages for the moment, like https://www.youtube.com/yt/copyright/ru/fair-use.html
