### ISSUE TITLE
Ability to disable GA statistics

### ISSUE THREAD

**Issue by Riajyuu** [james-fray/YouTube-No-Buffer#7]

**Comment by james-fray** [comment]
This extension does not use GA at all!

**Comment by copy** [comment]
@james-fray He may be referring to this from the `about:addons` page:

> Please note that the FAQs page of this extension contains Google Analytics; Terms can be found https://www.google.com/analytics/terms/us.html

Could you clarify whether GA runs on that page (or remove the text if it doesn't)?
